name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Set the branch you want to trigger the workflow on
  pull_request:
    branches:
      - main  # Set the branch you want to trigger the workflow on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build the Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: false  # Set to true if you want to push to a container registry
          tags: mlops-sentimental-analysis-app:latest  # Replace with your image name

      - name: Run Tests
        run: |
          docker run --rm mlops-sentimental-analysis-app:latest python -m unittest discover  # Replace with your test command

      - name: Deploy
        run: |
          echo "Deploying your application..."
          # Add your deployment commands here, e.g., SSH to your server, Docker commands, etc.
