name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Set the branch you want to trigger the workflow on
  pull_request:
    branches:
      - main  # Set the branch you want to trigger the workflow on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build the Docker image
        run: docker build -t ishwaryathirumurugan05/mlops-sentimental-analysis-app:latest .

      - name: Run Tests
        run: docker run --rm ishwaryathirumurugan05/mlops-sentimental-analysis-app:latest python -m unittest discover

      - name: Deploy
        run: |
          echo "Deploying your application..."
          # Add your deployment commands here, e.g., SSH to your server, Docker commands, etc.
